name: "Nix"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      run: git clone -b "yusdacra/chore/nix" --depth 1 https://gitlab.com/veloren/dev/veloren.git .
    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - name: Git LFS Pull
      run: git lfs pull

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: veloren-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix build --no-link -L --show-trace
